# test_profile:
#   target: dev
#   outputs:
#     dev:
#       type: postgres
#       host: postgres-sakila
#       user: postgres
#       password: postgres
#       port: 5433
#       dbname: postgres
#       schema: public
#       threads: 1


# my_dbt_trino_project:
#   target: dev
#   outputs:
#     dev:
#       type: trino
#       method: none
#       user: admin
#       database: datalake
#       # host: localhost
#       # host: 192.168.100.34
#       host: 192.168.100.8
#       # host: 172.20.0.12
#       port: 8089
#       schema: analytics
#       threads: 1


dbt_crime:
  target: dev
  outputs:
    dev:
      type: postgres
      host: host.docker.internal
      user: tsuser
      password: tspassword
      port: 5435
      dbname: tsdb
      schema: analytic
      threads: 1

